//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBooking.RyanairDataCollectorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlightS", Namespace="http://schemas.datacontract.org/2004/07/EasyBooking.Models.ViewModels")]
    [System.SerializableAttribute()]
    public partial class FlightS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArrivalCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ArrivalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartureCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DepartureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeatsEconomyclassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeatsFirstclassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArrivalCity {
            get {
                return this.ArrivalCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrivalCityField, value) != true)) {
                    this.ArrivalCityField = value;
                    this.RaisePropertyChanged("ArrivalCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ArrivalDate {
            get {
                return this.ArrivalDateField;
            }
            set {
                if ((this.ArrivalDateField.Equals(value) != true)) {
                    this.ArrivalDateField = value;
                    this.RaisePropertyChanged("ArrivalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartureCity {
            get {
                return this.DepartureCityField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartureCityField, value) != true)) {
                    this.DepartureCityField = value;
                    this.RaisePropertyChanged("DepartureCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DepartureDate {
            get {
                return this.DepartureDateField;
            }
            set {
                if ((this.DepartureDateField.Equals(value) != true)) {
                    this.DepartureDateField = value;
                    this.RaisePropertyChanged("DepartureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightCode {
            get {
                return this.FlightCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightCodeField, value) != true)) {
                    this.FlightCodeField = value;
                    this.RaisePropertyChanged("FlightCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeatsEconomyclass {
            get {
                return this.SeatsEconomyclassField;
            }
            set {
                if ((this.SeatsEconomyclassField.Equals(value) != true)) {
                    this.SeatsEconomyclassField = value;
                    this.RaisePropertyChanged("SeatsEconomyclass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeatsFirstclass {
            get {
                return this.SeatsFirstclassField;
            }
            set {
                if ((this.SeatsFirstclassField.Equals(value) != true)) {
                    this.SeatsFirstclassField = value;
                    this.RaisePropertyChanged("SeatsFirstclass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RyanairDataCollectorService.IRyanairDataCollector")]
    public interface IRyanairDataCollector {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRyanairDataCollector/GetFromRyanair", ReplyAction="http://tempuri.org/IRyanairDataCollector/GetFromRyanairResponse")]
        EasyBooking.RyanairDataCollectorService.FlightS[] GetFromRyanair(System.DateTime ArrivalDate, string fromCity, string toCity, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRyanairDataCollector/GetFromRyanair", ReplyAction="http://tempuri.org/IRyanairDataCollector/GetFromRyanairResponse")]
        System.Threading.Tasks.Task<EasyBooking.RyanairDataCollectorService.FlightS[]> GetFromRyanairAsync(System.DateTime ArrivalDate, string fromCity, string toCity, string userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRyanairDataCollectorChannel : EasyBooking.RyanairDataCollectorService.IRyanairDataCollector, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RyanairDataCollectorClient : System.ServiceModel.ClientBase<EasyBooking.RyanairDataCollectorService.IRyanairDataCollector>, EasyBooking.RyanairDataCollectorService.IRyanairDataCollector {
        
        public RyanairDataCollectorClient() {
        }
        
        public RyanairDataCollectorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RyanairDataCollectorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RyanairDataCollectorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RyanairDataCollectorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EasyBooking.RyanairDataCollectorService.FlightS[] GetFromRyanair(System.DateTime ArrivalDate, string fromCity, string toCity, string userId) {
            return base.Channel.GetFromRyanair(ArrivalDate, fromCity, toCity, userId);
        }
        
        public System.Threading.Tasks.Task<EasyBooking.RyanairDataCollectorService.FlightS[]> GetFromRyanairAsync(System.DateTime ArrivalDate, string fromCity, string toCity, string userId) {
            return base.Channel.GetFromRyanairAsync(ArrivalDate, fromCity, toCity, userId);
        }
    }
}
